# Generated by Django 3.1.1 on 2020-09-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200912_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.pessoa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.produto')),
            ],
        ),
    ]
