# Generated by Django 3.1.1 on 2020-09-14 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200914_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
