# Generated by Django 3.1.1 on 2020-09-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='my_app.produto'),
        ),
    ]
